ci: Fix dependency installation
Composer now requires plug-ins to be explicitly whitelisted before running them, see https://getcomposer.org/allow-plugins
When that is not done, installation will fail with:

    Error: phpstan/extension-installer contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.